def aircraft_catalog() -> list:
    aircraft_catalog_list = [
        {
            "aircraft_ID": "001",
            "manufacturer": "Airbus",
            "model": "A340-300",
            "required_crew": 10,
            "passengers_capacity": 295,
            "ticket_price": 20.0,
            "optimal_range_km": 4_400,
            "financials": {
                "price": 70_000_000,
                "annual_maintenance_cost": 3_500_000,
                "daily_operating_cost": 6_000,
                "daily_net_profit": 5_000,
            },
            "operations_24h": {"flights_per_24h": 1},
            "environmental_impact": {
                "co2_emissions_per_km": 12.5,
                "co2_rating": 6.0,
            },
        },
        {
            "aircraft_ID": "002",
            "manufacturer": "Airbus",
            "model": "A318",
            "required_crew": 5,
            "passengers_capacity": 132,
            "ticket_price": 16.0,
            "optimal_range_km": 1_250,
            "financials": {
                "price": 77_400_000,
                "annual_maintenance_cost": 1_200_000,
                "daily_operating_cost": 1_000,
                "daily_net_profit": 3_000,
            },
            "operations_24h": {"flights_per_24h": 6},
            "environmental_impact": {
                "co2_emissions_per_km": 7.8,
                "co2_rating": 7.0,
            },
        },
        {
            "aircraft_ID": "003",
            "manufacturer": "Airbus",
            "model": "A330-200",
            "required_crew": 11,
            "passengers_capacity": 247,
            "ticket_price": 45.0,
            "optimal_range_km": 2_850,
            "financials": {
                "price": 238_500_000,
                "annual_maintenance_cost": 2_200_000,
                "daily_operating_cost": 76_000,
                "daily_net_profit": 130_000,
            },
            "operations_24h": {"flights_per_24h": 2},
            "environmental_impact": {
                "co2_emissions_per_km": 11.2,
                "co2_rating": 7.4,
            },
        },
        {
            "aircraft_ID": "004",
            "manufacturer": "Airbus",
            "model": "A320ceo",
            "required_crew": 6,
            "passengers_capacity": 180,
            "ticket_price": 22.0,
            "optimal_range_km": 1_700,
            "financials": {
                "price": 101_000_000,
                "annual_maintenance_cost": 1_100_000,
                "daily_operating_cost": 3_000,
                "daily_net_profit": 6_000,
            },
            "operations_24h": {"flights_per_24h": 3},
            "environmental_impact": {
                "co2_emissions_per_km": 6.8,
                "co2_rating": 7.7,
            },
        },
        {
            "aircraft_ID": "005",
            "manufacturer": "Airbus",
            "model": "A380-800",
            "required_crew": 21,
            "passengers_capacity": 525,
            "ticket_price": 46.0,
            "optimal_range_km": 6_500,
            "financials": {
                "price": 445_600_000,
                "annual_maintenance_cost": 6_000_000,
                "daily_operating_cost": 15_000,
                "daily_net_profit": 29_000,
            },
            "operations_24h": {"flights_per_24h": 1},
            "environmental_impact": {
                "co2_emissions_per_km": 22.0,
                "co2_rating": 7.9,
            },
        },
        {
            "aircraft_ID": "006",
            "manufacturer": "Airbus",
            "model": "A330-900neo",
            "required_crew": 10,
            "passengers_capacity": 287,
            "ticket_price": 52.0,
            "optimal_range_km": 4_400,
            "financials": {
                "price": 296_400_000,
                "annual_maintenance_cost": 1_800_000,
                "daily_operating_cost": 4_000,
                "daily_net_profit": 15_000,
            },
            "operations_24h": {"flights_per_24h": 1},
            "environmental_impact": {
                "co2_emissions_per_km": 9.5,
                "co2_rating": 8.2,
            },
        },
        {
            "aircraft_ID": "007",
            "manufacturer": "Airbus",
            "model": "A350-900",
            "required_crew": 11,
            "passengers_capacity": 325,
            "ticket_price": 50.0,
            "optimal_range_km": 4_900,
            "financials": {
                "price": 317_400_000,
                "annual_maintenance_cost": 1_900_000,
                "daily_operating_cost": 6_000,
                "daily_net_profit": 23_000,
            },
            "operations_24h": {"flights_per_24h": 1},
            "environmental_impact": {
                "co2_emissions_per_km": 9.0,
                "co2_rating": 8.6,
            },
        },
        {
            "aircraft_ID": "008",
            "manufacturer": "Airbus",
            "model": "A320neo",
            "required_crew": 6,
            "passengers_capacity": 194,
            "ticket_price": 26.0,
            "optimal_range_km": 820,
            "financials": {
                "price": 110_600_000,
                "annual_maintenance_cost": 900_000,
                "daily_operating_cost": 2_500,
                "daily_net_profit": 7_000,
            },
            "operations_24h": {"flights_per_24h": 3},
            "environmental_impact": {
                "co2_emissions_per_km": 5.7,
                "co2_rating": 9.2,
            },
        },
        {
            "aircraft_ID": "009",
            "manufacturer": "Airbus",
            "model": "A220-300",
            "required_crew": 5,
            "passengers_capacity": 160,
            "ticket_price": 25.0,
            "optimal_range_km": 510,
            "financials": {
                "price": 91_500_000,
                "annual_maintenance_cost": 750_000,
                "daily_operating_cost": 2_600,
                "daily_net_profit": 7_000,
            },
            "operations_24h": {"flights_per_24h": 4},
            "environmental_impact": {
                "co2_emissions_per_km": 4.8,
                "co2_rating": 9.6,
            },
        },
        {
            "aircraft_ID": "010",
            "manufacturer": "Airbus",
            "model": "A321neo",
            "required_crew": 7,
            "passengers_capacity": 240,
            "ticket_price": 25.0,
            "optimal_range_km": 1_900,
            "financials": {
                "price": 129_500_000,
                "annual_maintenance_cost": 950_000,
                "daily_operating_cost": 3_000,
                "daily_net_profit": 12_000,
            },
            "operations_24h": {"flights_per_24h": 2},
            "environmental_impact": {
                "co2_emissions_per_km": 5.2,
                "co2_rating": 9.8,
            },
        },
    ]

    return aircraft_catalog_list
