def HUB_DESTINATIONS_CATALOG() -> list:
    HUB_DESTINATIONS_CATALOG = [
        # ============================================================
        # 1. FINLAND HUB: HEL (Helsinki-Vantaa Airport)
        # ============================================================
        {
            "hub_country": "Finland",
            "hub_code": "HEL",
            "hub_airport_name": "Helsinki-Vantaa Airport",
            "destinations": {
                "domestic": [
                    {
                        "country": "Finland",
                        "city": "Turku",
                        "airport_name": "Turku Airport",
                        "code": "TKU",
                        "distance_km": 150,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Finland",
                        "city": "Tampere",
                        "airport_name": "Tampere-Pirkkala Airport",
                        "code": "TMP",
                        "distance_km": 160,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Finland",
                        "city": "Oulu",
                        "airport_name": "Oulu Airport",
                        "code": "OUL",
                        "distance_km": 510,
                        "weather_severity": 2.2,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Finland",
                        "city": "Rovaniemi",
                        "airport_name": "Rovaniemi Airport",
                        "code": "RVN",
                        "distance_km": 700,
                        "weather_severity": 2.6,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Finland",
                        "city": "Kittilä",
                        "airport_name": "Kittilä Airport",
                        "code": "KTT",
                        "distance_km": 820,
                        "weather_severity": 2.8,
                        "runway_condition": 1.3,
                    },
                ],
                "regional_border": [
                    {
                        "country": "Estonia",
                        "city": "Tallinn",
                        "airport_name": "Tallinn Lennart Meri Airport",
                        "code": "TLL",
                        "distance_km": 100,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Latvia",
                        "city": "Riga",
                        "airport_name": "Riga International Airport",
                        "code": "RIX",
                        "distance_km": 360,
                        "weather_severity": 1.7,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Sweden",
                        "city": "Stockholm",
                        "airport_name": "Stockholm Arlanda Airport",
                        "code": "ARN",
                        "distance_km": 400,
                        "weather_severity": 1.8,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Lithuania",
                        "city": "Vilnius",
                        "airport_name": "Vilnius Airport",
                        "code": "VNO",
                        "distance_km": 630,
                        "weather_severity": 1.6,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Norway",
                        "city": "Oslo",
                        "airport_name": "Oslo Airport Gardermoen",
                        "code": "OSL",
                        "distance_km": 780,
                        "weather_severity": 2.1,
                        "runway_condition": 1.0,
                    },
                ],
                "international": [
                    {
                        "country": "United Kingdom",
                        "city": "London",
                        "airport_name": "London Heathrow Airport",
                        "code": "LHR",
                        "distance_km": 1_850,
                        "weather_severity": 1.9,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "France",
                        "city": "Paris",
                        "airport_name": "Paris Charles de Gaulle Airport",
                        "code": "CDG",
                        "distance_km": 1_900,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Turkey",
                        "city": "Istanbul",
                        "airport_name": "Istanbul Airport",
                        "code": "IST",
                        "distance_km": 2_150,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Egypt",
                        "city": "Cairo",
                        "airport_name": "Cairo International Airport",
                        "code": "CAI",
                        "distance_km": 3_400,
                        "weather_severity": 1.2,
                        "runway_condition": 1.3,
                    },
                    {
                        "country": "Saudi Arabia",
                        "city": "Riyadh",
                        "airport_name": "King Khalid International Airport",
                        "code": "RUH",
                        "distance_km": 4_300,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United Arab Emirates",
                        "city": "Dubai",
                        "airport_name": "Dubai International Airport",
                        "code": "DXB",
                        "distance_km": 4_500,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "China",
                        "city": "Beijing",
                        "airport_name": "Beijing Capital International Airport",
                        "code": "PEK",
                        "distance_km": 6_300,
                        "weather_severity": 1.7,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "New York",
                        "airport_name": "John F. Kennedy International Airport",
                        "code": "JFK",
                        "distance_km": 6_600,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "Washington D.C.",
                        "airport_name": "Washington Dulles International Airport",
                        "code": "IAD",
                        "distance_km": 7_000,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Japan",
                        "city": "Tokyo",
                        "airport_name": "Narita International Airport",
                        "code": "NRT",
                        "distance_km": 7_800,
                        "weather_severity": 1.9,
                        "runway_condition": 1.0,
                    },
                ],
            },
        },
        # ============================================================
        # 2. SWEDEN HUB: ARN (Stockholm Arlanda Airport)
        # ============================================================
        {
            "hub_country": "Sweden",
            "hub_code": "ARN",
            "hub_airport_name": "Stockholm Arlanda Airport",
            "destinations": {
                "domestic": [
                    {
                        "country": "Sweden",
                        "city": "Gothenburg",
                        "airport_name": "Gothenburg Landvetter Airport",
                        "code": "GOT",
                        "distance_km": 400,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Sweden",
                        "city": "Umeå",
                        "airport_name": "Umeå Airport",
                        "code": "UME",
                        "distance_km": 470,
                        "weather_severity": 2.2,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Sweden",
                        "city": "Malmö",
                        "airport_name": "Malmö Airport",
                        "code": "MMX",
                        "distance_km": 530,
                        "weather_severity": 1.5,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Sweden",
                        "city": "Luleå",
                        "airport_name": "Luleå Airport",
                        "code": "LLA",
                        "distance_km": 690,
                        "weather_severity": 2.5,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Sweden",
                        "city": "Kiruna",
                        "airport_name": "Kiruna Airport",
                        "code": "KRN",
                        "distance_km": 950,
                        "weather_severity": 2.9,
                        "runway_condition": 1.3,
                    },
                ],
                "regional_border": [
                    {
                        "country": "Norway",
                        "city": "Oslo",
                        "airport_name": "Oslo Airport Gardermoen",
                        "code": "OSL",
                        "distance_km": 385,
                        "weather_severity": 2.1,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Estonia",
                        "city": "Tallinn",
                        "airport_name": "Tallinn Lennart Meri Airport",
                        "code": "TLL",
                        "distance_km": 390,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Finland",
                        "city": "Helsinki",
                        "airport_name": "Helsinki-Vantaa Airport",
                        "code": "HEL",
                        "distance_km": 400,
                        "weather_severity": 1.9,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Denmark",
                        "city": "Copenhagen",
                        "airport_name": "Copenhagen Airport",
                        "code": "CPH",
                        "distance_km": 520,
                        "weather_severity": 1.5,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Germany",
                        "city": "Berlin",
                        "airport_name": "Berlin Brandenburg Airport",
                        "code": "BER",
                        "distance_km": 810,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                ],
                "international": [
                    {
                        "country": "United Kingdom",
                        "city": "London",
                        "airport_name": "London Heathrow Airport",
                        "code": "LHR",
                        "distance_km": 1_460,
                        "weather_severity": 1.9,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Spain",
                        "city": "Barcelona",
                        "airport_name": "Josep Tarradellas Barcelona-El Prat Airport",
                        "code": "BCN",
                        "distance_km": 2_280,
                        "weather_severity": 1.1,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Turkey",
                        "city": "Antalya",
                        "airport_name": "Antalya Airport",
                        "code": "AYT",
                        "distance_km": 2_690,
                        "weather_severity": 1.2,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Egypt",
                        "city": "Cairo",
                        "airport_name": "Cairo International Airport",
                        "code": "CAI",
                        "distance_km": 3_420,
                        "weather_severity": 1.2,
                        "runway_condition": 1.3,
                    },
                    {
                        "country": "Saudi Arabia",
                        "city": "Jeddah",
                        "airport_name": "King Abdulaziz International Airport",
                        "code": "JED",
                        "distance_km": 4_530,
                        "weather_severity": 1.5,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United Arab Emirates",
                        "city": "Dubai",
                        "airport_name": "Dubai International Airport",
                        "code": "DXB",
                        "distance_km": 4_760,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United States",
                        "city": "New York",
                        "airport_name": "John F. Kennedy International Airport",
                        "code": "JFK",
                        "distance_km": 6_300,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "Washington D.C.",
                        "airport_name": "Washington Dulles International Airport",
                        "code": "IAD",
                        "distance_km": 6_700,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "China",
                        "city": "Beijing",
                        "airport_name": "Beijing Capital International Airport",
                        "code": "PEK",
                        "distance_km": 7_350,
                        "weather_severity": 1.7,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Thailand",
                        "city": "Bangkok",
                        "airport_name": "Suvarnabhumi Airport",
                        "code": "BKK",
                        "distance_km": 8_200,
                        "weather_severity": 2.0,
                        "runway_condition": 1.1,
                    },
                ],
            },
        },
        # ============================================================
        # 3. GERMANY HUB: BER (Berlin Brandenburg Airport)
        # ============================================================
        {
            "hub_country": "Germany",
            "hub_code": "BER",
            "hub_airport_name": "Berlin Brandenburg Airport",
            "destinations": {
                "domestic": [
                    {
                        "country": "Germany",
                        "city": "Hamburg",
                        "airport_name": "Hamburg Airport",
                        "code": "HAM",
                        "distance_km": 260,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Germany",
                        "city": "Frankfurt",
                        "airport_name": "Frankfurt Airport",
                        "code": "FRA",
                        "distance_km": 430,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Germany",
                        "city": "Cologne",
                        "airport_name": "Cologne Bonn Airport",
                        "code": "CGN",
                        "distance_km": 470,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Germany",
                        "city": "Munich",
                        "airport_name": "Munich Airport",
                        "code": "MUC",
                        "distance_km": 480,
                        "weather_severity": 1.5,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Germany",
                        "city": "Stuttgart",
                        "airport_name": "Stuttgart Airport",
                        "code": "STR",
                        "distance_km": 510,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                ],
                "regional_border": [
                    {
                        "country": "Czech Republic",
                        "city": "Prague",
                        "airport_name": "Václav Havel Airport Prague",
                        "code": "PRG",
                        "distance_km": 280,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Poland",
                        "city": "Warsaw",
                        "airport_name": "Warsaw Chopin Airport",
                        "code": "WAW",
                        "distance_km": 520,
                        "weather_severity": 1.5,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Austria",
                        "city": "Vienna",
                        "airport_name": "Vienna International Airport",
                        "code": "VIE",
                        "distance_km": 520,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Netherlands",
                        "city": "Amsterdam",
                        "airport_name": "Amsterdam Airport Schiphol",
                        "code": "AMS",
                        "distance_km": 580,
                        "weather_severity": 1.8,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Switzerland",
                        "city": "Zurich",
                        "airport_name": "Zurich Airport",
                        "code": "ZRH",
                        "distance_km": 650,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                ],
                "international": [
                    {
                        "country": "Spain",
                        "city": "Palma de Mallorca",
                        "airport_name": "Palma de Mallorca Airport",
                        "code": "PMI",
                        "distance_km": 1_650,
                        "weather_severity": 1.1,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Turkey",
                        "city": "Istanbul",
                        "airport_name": "Istanbul Airport",
                        "code": "IST",
                        "distance_km": 1_730,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Egypt",
                        "city": "Hurghada",
                        "airport_name": "Hurghada International Airport",
                        "code": "HRG",
                        "distance_km": 3_280,
                        "weather_severity": 1.2,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Saudi Arabia",
                        "city": "Riyadh",
                        "airport_name": "King Khalid International Airport",
                        "code": "RUH",
                        "distance_km": 4_210,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Qatar",
                        "city": "Doha",
                        "airport_name": "Hamad International Airport",
                        "code": "DOH",
                        "distance_km": 4_370,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United Arab Emirates",
                        "city": "Dubai",
                        "airport_name": "Dubai International Airport",
                        "code": "DXB",
                        "distance_km": 4_620,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Kenya",
                        "city": "Nairobi",
                        "airport_name": "Jomo Kenyatta International Airport",
                        "code": "NBO",
                        "distance_km": 6_310,
                        "weather_severity": 1.8,
                        "runway_condition": 1.4,
                    },
                    {
                        "country": "United States",
                        "city": "New York",
                        "airport_name": "John F. Kennedy International Airport",
                        "code": "JFK",
                        "distance_km": 6_380,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "Washington D.C.",
                        "airport_name": "Washington Dulles International Airport",
                        "code": "IAD",
                        "distance_km": 6_780,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "China",
                        "city": "Beijing",
                        "airport_name": "Beijing Capital International Airport",
                        "code": "PEK",
                        "distance_km": 7_350,
                        "weather_severity": 1.7,
                        "runway_condition": 1.1,
                    },
                ],
            },
        },
        # ============================================================
        # 4. TURKEY HUB: IST (Istanbul Airport)
        # ============================================================
        {
            "hub_country": "Turkey",
            "hub_code": "IST",
            "hub_airport_name": "Istanbul Airport",
            "destinations": {
                "domestic": [
                    {
                        "country": "Turkey",
                        "city": "Izmir",
                        "airport_name": "Izmir Adnan Menderes Airport",
                        "code": "ADB",
                        "distance_km": 340,
                        "weather_severity": 1.2,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Turkey",
                        "city": "Ankara",
                        "airport_name": "Ankara Esenboğa Airport",
                        "code": "ESB",
                        "distance_km": 380,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Turkey",
                        "city": "Antalya",
                        "airport_name": "Antalya Airport",
                        "code": "AYT",
                        "distance_km": 510,
                        "weather_severity": 1.2,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Turkey",
                        "city": "Adana",
                        "airport_name": "Adana Şakirpaşa Airport",
                        "code": "ADA",
                        "distance_km": 700,
                        "weather_severity": 1.3,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Turkey",
                        "city": "Trabzon",
                        "airport_name": "Trabzon Airport",
                        "code": "TZX",
                        "distance_km": 900,
                        "weather_severity": 2.3,
                        "runway_condition": 1.4,
                    },
                ],
                "regional_border": [
                    {
                        "country": "Bulgaria",
                        "city": "Sofia",
                        "airport_name": "Sofia Airport",
                        "code": "SOF",
                        "distance_km": 500,
                        "weather_severity": 1.5,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Greece",
                        "city": "Athens",
                        "airport_name": "Athens International Airport",
                        "code": "ATH",
                        "distance_km": 560,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Romania",
                        "city": "Bucharest",
                        "airport_name": "Henri Coandă International Airport",
                        "code": "OTP",
                        "distance_km": 630,
                        "weather_severity": 1.5,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Cyprus",
                        "city": "Nicosia",
                        "airport_name": "Ercan International Airport",
                        "code": "ECN",
                        "distance_km": 750,
                        "weather_severity": 1.2,
                        "runway_condition": 1.3,
                    },
                    {
                        "country": "Georgia",
                        "city": "Tbilisi",
                        "airport_name": "Tbilisi International Airport",
                        "code": "TBS",
                        "distance_km": 1_330,
                        "weather_severity": 1.6,
                        "runway_condition": 1.2,
                    },
                ],
                "international": [
                    {
                        "country": "Syria",
                        "city": "Damascus",
                        "airport_name": "Damascus International Airport",
                        "code": "DAM",
                        "distance_km": 1_060,
                        "weather_severity": 1.4,
                        "runway_condition": 1.7,
                    },
                    {
                        "country": "Egypt",
                        "city": "Cairo",
                        "airport_name": "Cairo International Airport",
                        "code": "CAI",
                        "distance_km": 1_240,
                        "weather_severity": 1.2,
                        "runway_condition": 1.3,
                    },
                    {
                        "country": "Azerbaijan",
                        "city": "Baku",
                        "airport_name": "Heydar Aliyev International Airport",
                        "code": "GYD",
                        "distance_km": 1_680,
                        "weather_severity": 1.7,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Saudi Arabia",
                        "city": "Riyadh",
                        "airport_name": "King Khalid International Airport",
                        "code": "RUH",
                        "distance_km": 2_440,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United Kingdom",
                        "city": "London",
                        "airport_name": "London Heathrow Airport",
                        "code": "LHR",
                        "distance_km": 2_500,
                        "weather_severity": 1.9,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United Arab Emirates",
                        "city": "Dubai",
                        "airport_name": "Dubai International Airport",
                        "code": "DXB",
                        "distance_km": 3_000,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Uzbekistan",
                        "city": "Tashkent",
                        "airport_name": "Tashkent International Airport",
                        "code": "TAS",
                        "distance_km": 3_350,
                        "weather_severity": 1.5,
                        "runway_condition": 1.3,
                    },
                    {
                        "country": "China",
                        "city": "Beijing",
                        "airport_name": "Beijing Capital International Airport",
                        "code": "PEK",
                        "distance_km": 7_050,
                        "weather_severity": 1.7,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "New York",
                        "airport_name": "John F. Kennedy International Airport",
                        "code": "JFK",
                        "distance_km": 8_010,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "Washington D.C.",
                        "airport_name": "Washington Dulles International Airport",
                        "code": "IAD",
                        "distance_km": 8_400,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                ],
            },
        },
        # ============================================================
        # 5. SYRIA HUB: DAM (Damascus International Airport)
        # ============================================================
        {
            "hub_country": "Syria",
            "hub_code": "DAM",
            "hub_airport_name": "Damascus International Airport",
            "destinations": {
                "domestic": [
                    {
                        "country": "Syria",
                        "city": "Palmyra",
                        "airport_name": "Palmyra Airport",
                        "code": "PMS",
                        "distance_km": 210,
                        "weather_severity": 1.6,
                        "runway_condition": 2.2,
                    },
                    {
                        "country": "Syria",
                        "city": "Latakia",
                        "airport_name": "Latakia Airport",
                        "code": "LTK",
                        "distance_km": 230,
                        "weather_severity": 1.4,
                        "runway_condition": 1.6,
                    },
                    {
                        "country": "Syria",
                        "city": "Aleppo",
                        "airport_name": "Aleppo International Airport",
                        "code": "ALP",
                        "distance_km": 310,
                        "weather_severity": 1.4,
                        "runway_condition": 1.5,
                    },
                    {
                        "country": "Syria",
                        "city": "Deir ez-Zor",
                        "airport_name": "Deir ez-Zor Airport",
                        "code": "DEZ",
                        "distance_km": 420,
                        "weather_severity": 1.7,
                        "runway_condition": 2.0,
                    },
                    {
                        "country": "Syria",
                        "city": "Qamishli",
                        "airport_name": "Qamishli Airport",
                        "code": "KAC",
                        "distance_km": 520,
                        "weather_severity": 1.5,
                        "runway_condition": 2.0,
                    },
                ],
                "regional_border": [
                    {
                        "country": "Lebanon",
                        "city": "Beirut",
                        "airport_name": "Beirut–Rafic Hariri International Airport",
                        "code": "BEY",
                        "distance_km": 110,
                        "weather_severity": 1.3,
                        "runway_condition": 1.2,
                    },
                    {
                        "country": "Jordan",
                        "city": "Amman",
                        "airport_name": "Queen Alia International Airport",
                        "code": "AMM",
                        "distance_km": 180,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Egypt",
                        "city": "Cairo",
                        "airport_name": "Cairo International Airport",
                        "code": "CAI",
                        "distance_km": 610,
                        "weather_severity": 1.2,
                        "runway_condition": 1.3,
                    },
                    {
                        "country": "Iraq",
                        "city": "Baghdad",
                        "airport_name": "Baghdad International Airport",
                        "code": "BGW",
                        "distance_km": 750,
                        "weather_severity": 1.6,
                        "runway_condition": 1.5,
                    },
                    {
                        "country": "Turkey",
                        "city": "Istanbul",
                        "airport_name": "Istanbul Airport",
                        "code": "IST",
                        "distance_km": 1_060,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                ],
                "international": [
                    {
                        "country": "Saudi Arabia",
                        "city": "Riyadh",
                        "airport_name": "King Khalid International Airport",
                        "code": "RUH",
                        "distance_km": 1_420,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Qatar",
                        "city": "Doha",
                        "airport_name": "Hamad International Airport",
                        "code": "DOH",
                        "distance_km": 1_720,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "United Arab Emirates",
                        "city": "Dubai",
                        "airport_name": "Dubai International Airport",
                        "code": "DXB",
                        "distance_km": 2_050,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "Russia",
                        "city": "Moscow",
                        "airport_name": "Sheremetyevo International Airport",
                        "code": "SVO",
                        "distance_km": 2_470,
                        "weather_severity": 2.4,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Germany",
                        "city": "Berlin",
                        "airport_name": "Berlin Brandenburg Airport",
                        "code": "BER",
                        "distance_km": 2_720,
                        "weather_severity": 1.3,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "France",
                        "city": "Paris",
                        "airport_name": "Paris Charles de Gaulle Airport",
                        "code": "CDG",
                        "distance_km": 3_270,
                        "weather_severity": 1.4,
                        "runway_condition": 1.0,
                    },
                    {
                        "country": "China",
                        "city": "Beijing",
                        "airport_name": "Beijing Capital International Airport",
                        "code": "PEK",
                        "distance_km": 7_100,
                        "weather_severity": 1.7,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "Malaysia",
                        "city": "Kuala Lumpur",
                        "airport_name": "Kuala Lumpur International Airport",
                        "code": "KUL",
                        "distance_km": 7_400,
                        "weather_severity": 2.1,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "New York",
                        "airport_name": "John F. Kennedy International Airport",
                        "code": "JFK",
                        "distance_km": 9_000,
                        "weather_severity": 1.8,
                        "runway_condition": 1.1,
                    },
                    {
                        "country": "United States",
                        "city": "Washington D.C.",
                        "airport_name": "Washington Dulles International Airport",
                        "code": "IAD",
                        "distance_km": 9_350,
                        "weather_severity": 1.6,
                        "runway_condition": 1.0,
                    },
                ],
            },
        },
    ]

    return HUB_DESTINATIONS_CATALOG
